### ISSUE TITLE
Can you share an example of how to use your table with a custom toolbar?

### ISSUE THREAD

**Issue by mohitsud** [zzxming/quill-table-up#15]
I love your plugin and want to use it but I am not sure how to get it to work with a custom tool bar.

Do you have any advice?

**Comment by zzxming** [comment]
Do you want to customize the content of this section?

![image](https://github.com/user-attachments/assets/1f6217a1-fe00-48b1-83ef-b9c9faf47147)

You can use the option `customSelect`
