### ISSUE TITLE
Is there any functionality to remove table borders?

### ISSUE THREAD

**Issue by pratyushprakash** [zzxming/quill-table-up#17]
I want to use a table to structure the content but don't want to show the borders. Eg, columnar text

**Comment by zzxming** [comment]
Just use CSS to set `td { boder: none }`

**Comment by pratyushprakash** [comment]
Ah ok, thanks.

Also, do you know if html will render with https://www.npmjs.com/package/quill-delta-to-html?

**Comment by zzxming** [comment]
You mean html string render to editor? I haven't used this package before. I don't know if it can be directly rendered using HTML. but quill module `clipboard` have a function name [`dangerouslyPasteHTML`](https://quilljs.com/docs/modules/clipboard#dangerouslypastehtml). that can render html string to editor.

**Comment by pratyushprakash** [comment]
No, I meant convert the quill edotor content to HTML

**Comment by zzxming** [comment]
[`getSemanticHTML`](https://quilljs.com/docs/api#getsemantichtml) can do this

**Comment by pratyushprakash** [comment]
Thanks @zzxming , I will try it out
