### ISSUE TITLE
How to remove border and align the table to right or center

### ISSUE THREAD

**Issue by isaacfi** [zzxming/quill-table-up#20]
Hi @zzxming ,

Your module is great and I'm starting using it but I don't know how to align the table and I was not able to remove or change the color of the border of cells. Could you provide some info about that?

Thanks!

**Comment by zzxming** [comment]
At present, the table can only be left aligned, but you can use set css `margin-left: auto` in `table` to make it aligned right. or set `margin: auto` to align them to the center. and the border color can be changed using CSS

Maybe I should add these two functions to the module, as they are very useful features

**Comment by zzxming** [comment]
Hi. I have released version 1.5.0, which supports modifying cell border colors and overall table alignment. You can give it a try.

**Comment by isaacfi** [comment]
Thanks @zzxming,

The new functionality is amazing, it's what I expected.

Great job!
