### ISSUE TITLE
Paste text from browser or word

### ISSUE THREAD

**Issue by ahmedelhanony** [zzxming/quill-table-up#25]
Hi @zzxming 
Your module is great and I'm starting using it but I have an issue when tring to paste text from browser or word in a table, it breaks the table into 2 tables. is there any way to fix this issue or give me an example to ovveride thise issue.

Thanks

**Comment by zzxming** [comment]
Thanks for report. It's a bug. I will handle it

**Comment by zzxming** [comment]
Hi. I have released version 1.5.1, which fix this issue. You can give it a try.

**Comment by ahmedelhanony** [comment]
It works, thanks! Great work. Really appreciate your effort in fixing this so quickly.

**Comment by zzxming** [comment]
> It works, thanks! Great work. Really appreciate your effort in fixing this so quickly.

Thank you for using this module and giving me feedback😊
