### ISSUE TITLE
The background color selector will disappear

### ISSUE THREAD

**Issue by ybj6118** [zzxming/quill-table-up#30]
When the mouse moves to the color picker, it will disappear
![20241203-121312](https://github.com/user-attachments/assets/d1609593-108f-4d51-93a8-831ebb70ae05)

**Comment by zzxming** [comment]
Thanks for report. I tested this issue, and the reason may be that during the movement, the mouse moved to the page position between the popup and the selector, as shown in the red box selection range in the image below, which triggered mouseleave and closed the selector.

![image](https://github.com/user-attachments/assets/968be1ac-4d0a-48a2-9a02-41ae4858c8b0)

I wil handle this issue when I have free time
