### ISSUE TITLE
Is there a way to prevent cell resizing?

### ISSUE THREAD

**Issue by tourniayrem** [zzxming/quill-table-up#37]
Hello, first of all, great library!

I was wondering if it was possible to prevent cell size modification?

![image](https://github.com/user-attachments/assets/501d9ba5-1220-428d-903e-ab8ff48a54ac)

**Comment by zzxming** [comment]
for now you can't disable cell resizer, but I'm working on it. in next version you can disable certain features by configuring them

**Comment by zzxming** [comment]
for now you can't disable cell resizer, but I'm working on it. in next version you can disable certain features by configuring them

**Comment by zzxming** [comment]
Version 2.0.0 accepts configuring internal modules and can tree shake unused modules. You can try it out. But there are breaking changes, please pay attention to the configuration changes.
