### ISSUE TITLE
Error when using this.quill.clipboard.convert(XXX) in version >=1.5

### ISSUE THREAD

**Issue by tourniayrem** [zzxming/quill-table-up#38]
I have this code which sets the content of my editor to the content saved last time
```
const contents = this.quill.clipboard.convert(this.content);
this.quill.setContents(contents);
```
`this.content` is a string that contains html content such as `<p>test</p>`

With this, no problem but as soon as `this.content` contains a table in it (so `<p>test</p><div class="ql-table-wrapper" ..."`) i got this error:

`TypeError: Cannot read properties of undefined (reading 'attributes')
    at index.js:4009:16
    at clipboard.js:274:18
    at Array.reduce (<anonymous>)
    at clipboard.js:273:60
    at Array.reduce (<anonymous>)
    at traverse (clipboard.js:267:46)
    at clipboard.js:268:27
    at Array.reduce (<anonymous>)
    at traverse (clipboard.js:267:46)
    at clipboard.js:268:27`
 
Version used:
* quill: 2.0.3
* quill-table-up: 1.6 (same with 1.5.2 but works perfectly in 1.4)
* parchment: 3.0.0

**Comment by zzxming** [comment]
`quill.clipboard.convert` need a object like `{ html?: string, text?: string}`, not a string. here is the convert type define

```ts
convert({ html, text }: {
    html?: string;
    text?: string;
}, formats?: Record<string, unknown>): Delta;
```

you should use like this. and I test it, it works on 1.6.0. here is [demo](https://stackblitz.com/edit/vitejs-vite-bxf6tu?file=package.json)
```js
const contents = quill1.clipboard.convert({
  html: content, // content is html string
});
quill.setContents(contents);
```

**Comment by tourniayrem** [comment]
You're right and I sent the wrong code, I indeed have `this.quill.clipboard.convert({html : this.content});`

**Comment by zzxming** [comment]
> After further investigation, the error came from ngx-quill, a wrapper around quill for angular.

seem like the error not from `quill-table-up`. I will close this issue. If there are any question, you can reopen it
